[package]
name = "webproxy"
version = "0.1.0"
authors = ["Christopher O'Neill <code@chrisoneill.co.uk>"]
description = "A simple web proxy"
keywords = ["webproxy", "proxy"]
# license = ""

[dependencies]
log = "*"
env_logger = "*"
